# Generated by Django 5.1.4 on 2025-05-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_category_name_en_category_name_ru_news_text_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('AR', 'Article'), ('NW', 'News')], default='NW', max_length=2),
        ),
    ]
